### ISSUE TITLE
Tooltips shouldn't be clickable

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#1915]
## Description

Tooltips needs some fine-tuning.

## Expected behavior 

Tooltips should be non-interactive.

## Actual behavior 

Often when I want to click on a thing with tooltip, the row above is clicked instead, e.g.:
<img width="236" alt="screen shot 2018-08-07 at 18 38 32" src="https://user-images.githubusercontent.com/2521888/43789796-2f181e2c-9a71-11e8-9857-dfb4e43f2be2.png">

## Additional details

This is the fix I used few times, I feel it should be global:

```css
[data-tooltip]::before,
[data-tooltip]::after {
  pointer-events: none;
}
```
