### ISSUE TITLE
Upgrade from 2.022.44b to 2.023.12b with postgres 10.12 fails

### ISSUE THREAD

**Issue by wozniakpl** [kobotoolbox/kpi#4546]
## Description

Can't upgrade from 2.022.44b to 2.023.12b with postgres in version 10.12.
I couldn't find any constraints regarding postgres version, so correct me if I'm using something wrong here.

## Steps to Reproduce

1. Create such `docker-compose.yml`:
```
version: '3'

services:
  kpi:
    image: kobotoolbox/kpi:2.022.44b
    # image: kobotoolbox/kpi:2.023.12b
    environment:
      - DATABASE_URL=postgres://kobo:kobo@postgres:5432/koboform
      - KC_DATABASE_URL=postgres://kobo:kobo@postgres:5432/kobocat
      - KPI_PREFIX=/
    volumes:
      - ./wait_for_mongo.bash:/srv/init/wait_for_mongo.bash
      - ./wait_for_postgres.bash:/srv/init/wait_for_postgres.bash
      - ./media:/srv/src/kpi/media
    depends_on:
      - postgres

  postgres:
    image: postgres:10.12
    environment:
      POSTGRES_USER: kobo
      POSTGRES_PASSWORD: kobo
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
```

Provide empty `wait_for_*` scripts - e.g. `sleep 2` inside.
`init.sql` looks like this:
```
CREATE DATABASE koboform;
CREATE DATABASE kobocat;
```

2. Start all:
```
docker compose up --build -d
docker compose logs
```
And wait until migrations pass.

3. Change the image in docker-compose (from 2.022.44 to 2.023.12)
4. Up again
```
docker compose up --build -d
docker compose logs
```
5. Error appears

## Expected behavior 

Migrations pass.

## Actual behavior 

Migrations fail:
```
temp-kpi-1       |   Applying hub.0008_add_removal_dates_to_extrauserdetail... OK
temp-postgres-1  | 2023-07-19 11:40:57.927 UTC [58] ERROR:  cannot ALTER TABLE "hub_extrauserdetail" because it has pending trigger events
temp-postgres-1  | 2023-07-19 11:40:57.927 UTC [58] STATEMENT:  ALTER TABLE "hub_extrauserdetail" ADD CONSTRAINT "hub_extrauserdetail_uid_df45cb35_uniq" UNIQUE ("uid")
temp-kpi-1       | Traceback (most recent call last):
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
temp-kpi-1       |     return self.cursor.execute(sql, params)
temp-kpi-1       | psycopg2.errors.ObjectInUse: cannot ALTER TABLE "hub_extrauserdetail" because it has pending trigger events
temp-kpi-1       | 
temp-kpi-1       | 
temp-kpi-1       | The above exception was the direct cause of the following exception:
temp-kpi-1       | 
temp-kpi-1       | Traceback (most recent call last):
temp-kpi-1       |   File "/srv/src/kpi/manage.py", line 10, in <module>
temp-kpi-1       |     execute_from_command_line(sys.argv)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
temp-kpi-1       |     utility.execute()
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
temp-kpi-1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
temp-kpi-1       |     self.execute(*args, **cmd_options)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
temp-kpi-1       |     output = self.handle(*args, **options)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
temp-kpi-1       |     res = handle_func(*args, **kwargs)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
temp-kpi-1       |     post_migrate_state = executor.migrate(
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
temp-kpi-1       |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
temp-kpi-1       |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
temp-kpi-1       |     state = migration.apply(state, schema_editor)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
temp-kpi-1       |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
temp-kpi-1       |     schema_editor.alter_field(from_model, from_field, to_field)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
temp-kpi-1       |     self._alter_field(model, old_field, new_field, old_type, new_type,
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/schema.py", line 196, in _alter_field
temp-kpi-1       |     super()._alter_field(
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 800, in _alter_field
temp-kpi-1       |     self.execute(self._create_unique_sql(model, [new_field.column]))
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 145, in execute
temp-kpi-1       |     cursor.execute(sql, params)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
temp-kpi-1       |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
temp-kpi-1       |     return executor(sql, params, many, context)
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
temp-kpi-1       |     with self.db.wrap_database_errors:
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
temp-kpi-1       |     raise dj_exc_value.with_traceback(traceback) from exc_value
temp-kpi-1       |   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
temp-kpi-1       |     return self.cursor.execute(sql, params)
temp-kpi-1       | django.db.utils.OperationalError: cannot ALTER TABLE "hub_extrauserdetail" because it has pending trigger events
temp-kpi-1       | 
temp-kpi-1 exited with code 1
```
