### ISSUE TITLE
Data Table column background should not be transparent

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4764]
## Description

If there is a frozen column with sorting in Data Table, the data is hard to read due to transparent teal background. It should not be transparent :)

<img width="383" alt="Screenshot 2023-12-14 at 15 38 31" src="https://github.com/kobotoolbox/kpi/assets/2521888/13743d2a-a337-4ff3-a8cd-21920413ec9c">
<img width="356" alt="Screenshot 2023-12-14 at 15 39 40" src="https://github.com/kobotoolbox/kpi/assets/2521888/cd307dc0-69ea-4461-912a-32c7dca85753">

Also notice in `table.scss` file that we have two lines of code:

```scss
  .rt-th.is-sorted {
    background-color: rgba(colors.$kobo-light-teal, 0.5);
  }

  .rt-td.is-sorted {
    background-color: rgba(colors.$kobo-light-teal, 0.2);
  }
```

This suggest we have a connected bug - the header cells should also appear teal colored when `is-sorted` is applied. And the problem is that it is not being applied 👎
